In [3]:
import numpy as np

### 2 Layers Neural Network

In [4]:
X = [[0.2, 0.3, 0.5]]

W1 = np.array([[2, -1, 1, 5], [1, -1, 2, 3], [-2, 1, 2, -1]])
W2 = np.array([[1,-1, 2, 3], [-1,-1,2,3],[-2,1,1,-2], [-1,-1,2,2]])
W3 = np.array([[3,1,-2], [1,-1,3], [-1,2,3], [1,-2,1]])

In [5]:
def softmax(z):
    Z = np.exp(z) / np.sum(np.exp(z))
    return Z

def sigmoid(z):
    return 1 / (1 + np.exp(-z))
    
def hidden_layer(X, W):
    z = np.dot(X, W)
    a = sigmoid(z) # sigmoid activation function
    print('W:',W)
    
    return a    

def output_layer(X, W):
    z = np.dot(X, W)
    a = softmax(z) # sigmoid activation function
    print('W:',W)
    return a

### Test

In [6]:
a0= hidden_layer(X, W1)
a1 = hidden_layer(a0, W2)
a2 = output_layer(a1, W3)
print(a2)



W: [[ 2 -1  1  5]
 [ 1 -1  2  3]
 [-2  1  2 -1]]
W: [[ 1 -1  2  3]
 [-1 -1  2  3]
 [-2  1  1 -2]
 [-1 -1  2  2]]
W: [[ 3  1 -2]
 [ 1 -1  3]
 [-1  2  3]
 [ 1 -2  1]]
[[0.01479786 0.00833321 0.97686894]]


# Skitlearn

In [7]:
from sklearn.neural_network import MLPClassifier
import numpy as np 

In [8]:
mlp = MLPClassifier(hidden_layer_sizes=(4,4), activation='logistic')

x_mat_in = np.array([[0.2, 0.3, 0.5], [0.2, 0.5, 0.1]])
x_train = x_mat_in
y_train = np.array([0, 2])
mlp.fit(x_train, y_train)

print('Weights assigned to the first hidde layer (W1):', mlp.coefs_[0])
print('Weights assigned to the first hidde layer (W1):', mlp.coefs_[1])
print('Weights assigned to the first hidde layer (W2):', mlp.coefs_[2])


Weights assigned to the first hidde layer (W1): [[-0.2085731  -0.34544332  0.36066027 -0.08846968]
 [-0.26977246 -0.33688163 -0.34826404 -0.16834394]
 [-0.26276579  0.05739325  0.27980807  0.05087891]]
Weights assigned to the first hidde layer (W1): [[-0.33423425 -0.03621379  0.07989706 -0.40775716]
 [ 0.30413755 -0.35737247  0.36223364  0.23877756]
 [ 0.08696112  0.45516316 -0.18618966  0.36737625]
 [ 0.09003409 -0.13170615  0.21386287 -0.06640797]]
Weights assigned to the first hidde layer (W2): [[-0.58164152]
 [ 0.57089408]
 [ 0.08574342]
 [ 0.1790537 ]]


In [9]:
x_in = np.array([0.2, 0.3, 0.5])
y = np.array([0])
# Reshape x_in to a 2D array as expected by MLPClassifier
x_in = x_in.reshape(1, -1)

mlp = MLPClassifier(hidden_layer_sizes=(4, 4), activation='logistic', solver='adam',
                    max_iter=100, random_state=1, warm_start=True)

mlp.fit (x_in, y)

mlp.coefs_[0] = np.array([[2, -1, 1, 5], [1, -1, 2, 3], [-2, 1, 2, -1]])
mlp.coefs_[1] = np.array([[1,-1, 2, 3], [-1,-1,2,3],[-2,1,1,-2], [-1,-1,2,2]])
mlp.coefs_[2] = np.array([[3,1,-2], [1,-1,3], [-1,2,3], [1,-2,1]])

# No bias terms are set in the original code so we set these to 0
mlp.intercepts_[0] = np.zeros(4)
mlp.intercepts_[1] = np.zeros(4)
mlp.intercepts_[2] = np.zeros(3)



# Make a prediction
output_act = mlp.predict_proba(x_in)
print(output_act)

W1 = mlp.coefs_[0]
W2 = mlp.coefs_[1]
W3 = mlp.coefs_[2]

b1 = mlp.intercepts_[0]
b2 = mlp.intercepts_[1]
b3 = mlp.intercepts_[2]

[[0.38882675 0.61117325]
 [0.53045917 0.46954083]
 [0.00954529 0.99045471]]


d:\CODE\IDE\Anaconda\envs\idd\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


In [13]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 
from tensorflow.keras import Input 
from tensorflow.keras.optimizers import SGD 
import tensorflow as tf

# Model
model = Sequential([
    Input(shape=(3,)),
    Dense(4, activation='sigmoid'),
    Dense(4, activation='sigmoid'),
    Dense(3, activation='softmax')        
])

model.compile(SGD(learning_rate=0.001),
               loss='categorical_crossentropy',
               metrics=['accuracy'])

print(model.summary())
output = model.predict(x_in.reshape(1, -1))
print(output)



Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_15 (Dense)                │ (None, 4)              │            16 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 51 (204.00 B)

 Trainable params: 51 (204.00 B)

 Non-trainable params: 0 (0.00 B)

None
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step
[[0.16044952 0.3813311  0.4582194 ]]
